---
- name: Testing andrewrothstein.pluto
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'pluto version'
      ansible.builtin.command: pluto version
      changed_when: false
      register: pluto_test_version
    - name: Output of 'pluto version'
      ansible.builtin.debug:
        msg: '{{ pluto_test_version.stdout }}'
