---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install in {{ pluto_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ pluto_exe }}'
  changed_when: false
  register: pluto_binary
- name: Downloading and installing pluto
  when: not pluto_binary.stat.exists
  block:
    - name: Downloading {{ pluto_url }} to {{ pluto_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ pluto_url }}'
        dest: '{{ pluto_tmp_tgz }}'
        mode: '644'
        checksum: '{{ pluto_checksum }}'
    - name: Mkdir {{ pluto_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ pluto_install_dir }}'
        mode: '755'
        state: directory
    - name: Unarchiving {{ pluto_tmp_tgz }} into {{ pluto_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ pluto_tmp_tgz }}'
        dest: '{{ pluto_install_dir }}'
        creates: '{{ pluto_exe }}'
  always:
    - name: Rm {{ pluto_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ pluto_tmp_tgz }}'
        state: absent
- name: Linking {{ pluto_link }} to {{ pluto_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ pluto_exe }}'
    dest: '{{ pluto_link }}'
    state: link
